### ISSUE TITLE
Greetings from South Korea: requesting for /population.csv

### ISSUE THREAD

**Issue by snoop2head** [Rank23/COVID19#1]
Greetings from South Korea.

It seems like Corona Virus crisis is surging here, so I would like to make Time Series forecast with your models. Tutorials of yours is the most accessible version that I can find in Github!

But I would like to request population.csv data, if possible, to be uploaded on github.
```python
population=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Optimization Course/population.csv', sep=',', encoding='latin1') 
```
is found to be missing, so I am trying to run the models without population.

Thank you, and thanks for sharing your work.

**Comment by Rank23** [comment]
Hi,
Thanks for your feedback and hopefully you will get control over the crisis there soon.
I've uploaded the population.csv file. 
Note that data out of China is provided per country and not per city/province, therefore population data is more general.
You can contact me for more inquiries - rank23@gmail.com
Regards.
