### ISSUE TITLE
region change

### ISSUE THREAD

**Issue by mohscorpion** [Rank23/COVID19#3]
hi
thanks for this great workshop, when i change region at this step:
train_h20 = h2o.H2OFrame(train_df)
train_h20_hubei = h2o.H2OFrame(train_df_hubei) # different model for Hubei
training_columns = ['region','1_day_change', '3_day_change', '7_day_change', '1_day_change_rate', '3_day_change_rate',
                    '7_day_change_rate', 'last_day', 'kalman_prediction','infected_rate', 'min', 'max'
                   ]                 
# Output parameter train against input parameters
response_column = 'confirmed'

# model = H2ORandomForestEstimator(ntrees=300, max_depth=12)
# model.train(x=training_columns, y=response_column, training_frame=train_h20)
model_hubei = H2ORandomForestEstimator(ntrees=300, max_depth=12)
model_hubei.train(x=training_columns, y=response_column, training_frame=train_h20_hubei)

test_h20 = h2o.H2OFrame(test)
#test_h20_hubei = h2o.H2OFrame(test_hubei)
i get this error :
/usr/local/lib/python3.6/dist-packages/h2o/backend/connection.py in _process_response(response, save_to)
    822         # Client errors (400 = "Bad Request", 404 = "Not Found", 412 = "Precondition Failed")
    823         if status_code in {400, 404, 412} and isinstance(data, (H2OErrorV3, H2OModelBuilderErrorV3)):
--> 824             raise H2OResponseError(data)
    825 
    826         # Server errors (notably 500 = "Server Error")
can you please help me find the error?
thanks

**Comment by Rank23** [comment]
Hi,
Did you successfully run h2o.init(min_mem_size='8G')?
Where did you try to change the region?

If you want to train the model on a single location you should change it before the code you mentioned, in the following line:
train_df_hubei=train_df[train_df['region']=='China_Hubei'] 
just replace 'China_Hubei'.

Note that I've tried to run a separate model for Hubei since most of the cases are in Hubei but it's not mandatory and reasonable to train the model over all possible regions.

**Comment by mohscorpion** [comment]
thanks for the fast reply , i found the problem , i also must have changed the date separating trainind and test data , it seemed that the date that was used in code , contained no data for training in that time span .

**Comment by mohscorpion** [comment]
i'll continue to report every result i get

**Comment by mohscorpion** [comment]
now i got till this part :
```
pred=reg.predict(test_iter[x_col]); pred=pd.DataFrame(pred); pred.columns = ['prediction'];pred=round(pred)
pred['confirmed']=test_iter['confirmed'].values; pred['date']=test_iter['date'].values; pred['region']=test_iter['region'].values
for i in range(1,len(pred)):
    if(pred.iloc[i,3] is pred.iloc[i-1,3]):
      if(pred.iloc[i,0]<pred.iloc[i-1,1]):
        pred.iloc[i,0]=pred.iloc[i-1,1]
pred=pred.pivot(index='date',columns='region',values='prediction') # pivot pred df
```
it shows this error 
```
ValueError                                Traceback (most recent call last)
<ipython-input-57-dfc5744b1f15> in <module>()
      5       if(pred.iloc[i,0]<pred.iloc[i-1,1]):
      6         pred.iloc[i,0]=pred.iloc[i-1,1]
----> 7 pred=pred.pivot(index='date',columns='region',values='prediction') # pivot pred df

5 frames
/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/reshape.py in _make_selectors(self)
    178 
    179         if mask.sum() < len(self.index):
--> 180             raise ValueError("Index contains duplicate entries, " "cannot reshape")
    181 
    182         self.group_index = comp_index

ValueError: Index contains duplicate entries, cannot reshape
```

**Comment by snoop2head** [comment]
That might happen when dataset updated by johns hopkins university is not evenly updated: some countries' data is updated whereas other regions are not. Wait for next few hours and try it again!

**Comment by Rank23** [comment]
Try to run the following line just before pred.pivot:
pred=pred.drop_duplicates(['date', 'region'],keep= 'first')

**Comment by mohscorpion** [comment]
thanks , it worked
