### ISSUE TITLE
1 day prediction

### ISSUE THREAD

**Issue by anonym0305** [Rank23/COVID19#8]
Hi - Great work. 

1) Why only a 1 day prediction ? Why not try to predict over a longer duration ? 2nd waves ?
2) Why not predict across multiple countries ?

**Comment by Rank23** [comment]
Hi,
1. Kalman filter is an iterative model that means every timestamp (1 day in our case) it needs to get feedback of updated data. Then, the model update parameters estimation and can produce a prediction for the next time. Predictions for longer periods are more challenging as we don't get updated measurements along the way. But still can be done approximately by predicting the general trend with some calculated noise.
2. The model tracks each region as a separated time series but absolutely can be upgraded and improve estimation based on other regions' time series as well. 
Regards,
Ran

**Comment by anonym0305** [comment]
Hi Ran - Do you want to chat offline ? I'm a prof. at a univ exploring the issue of 2nd waves. If you give me an email I'll reach out to you ? Thanks.

**Comment by Rank23** [comment]
Sure.
rank23@gmail.com
